[book]
title = "Осваиваем Ethereum - Mastering Ethereum"
authors = ["Andreas M. Antonopoulos", "Gavin Wood"]
description = "Руководство по Ethereum и разработке смарт-контрактов"
language = "ru"
multilingual = false
src = "src"
